title: CV_Hongfei Liu

aboutme:
  name:  Hongfei Liu
  sex:   Male
  birth: November 1, 1996
  email: liuhongfei@shu.edu.cn
  phone: (+86) 17721234957
  address: No.99 Shangda Road, Shanghai, China, 200444
  nationality: Chinese


